GET http://localhost:3000/events


###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "evento_1",
    "description": "este é o primeiro evento",
    "date": "2017-01-01T00:00:00.000Z",
    "price": 100   
}
